# Generated by Django 5.2 on 2025-04-23 09:41

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('player_ids', django.contrib.postgres.fields.hstore.HStoreField()),
                ('player1_username', models.CharField(max_length=150)),
                ('player1_sets', models.IntegerField(default=0)),
                ('player2_username', models.CharField(max_length=150)),
                ('player2_sets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner_username', models.CharField(max_length=150)),
                ('winner_id', models.CharField(max_length=150, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OngoingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100, unique=True)),
                ('player_ids', django.contrib.postgres.fields.hstore.HStoreField()),
                ('player1_username', models.CharField(max_length=150)),
                ('player1_sets', models.IntegerField(default=0)),
                ('player2_username', models.CharField(max_length=150)),
                ('player2_sets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
